if status is-interactive
    mise activate fish | source
else
    mise activate fish --shims | source
end

if status is-interactive
    # Commands to run in interactive sessions can go here
    atuin init fish | source
    starship init fish | source
    jump shell fish | source

    direnv hook fish | source

    if test -d /opt/homebrew
        /opt/homebrew/bin/brew shellenv | source
    end


    set -Ux EZA_STANDARD_OPTIONS --long --all

    alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"

    # kubectl-shell_ctx hook fish | source
    # flux completion fish | source
    # flux-operator completion fish | source
end

export EDITOR="cursor -w"
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/ajchristensen/google-cloud-sdk/path.fish.inc' ]
    . '/Users/ajchristensen/google-cloud-sdk/path.fish.inc'
end

# Generated by Groq bootstrap; START; DO NOT EDIT.
source $HOME/.config/groq-bootstrap/groq-bootstrap.fish
# Generated by Groq bootstrap; END; DO NOT EDIT.
